name: Scala CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install libs
        run: sudo apt-get install libgfortran3 libopenblas-base
      - name: Run tests
        run: sbt +test
